geemap.basemap does not contain function basemap
ImportError: cannot import name 'basemaps' from 'geemap.basemaps' (C:\Users\.abc\miniconda3\envs\geo\lib\site-packages\geemap\basemaps.py)

I am following the workshop from Youtube and received this error, 
and I am not sure whether this errors resulted from installing geemap using pip instead of conda.